#'
#' @title Calculate the weighted importance score for each peak
#'
#' @description
#' Replace missing values (NA) and calculate weighted importance scores for peaks.
#'
#' @param snp2peak_map Data frame generated by the 'snp2peak()' function.
#'                     Must contain columns 'snp_id', 'Significance', and 'Strength'.
#' @param w1 Weight of peak strength (peak-gene correlation, e.g., -log10(p-value)). Default = 0.5.
#' @param w2 Weight of peak significance (genetic relevance, e.g., -log10 SNP p-value). Default = 0.5.
#' @return A data frame where missing values are replaced and an 'Importance_weighted' column is added.
#' @details
#' - Replace NA in 'snp_id' with 'no_snp' and in 'Significance' with 0.
#' - Calculate weighted importance scores for each peak using the formula: `w1 * Strength + w2 * Significance`.
#' @export
#'
getPeakScore <- function(snp2peak_map, w1 = 0.3, w2 = 0.7) {
  # Step 1: Validate input
  # Check if required columns exist
  required_columns <- c("snp_id", "Significance", "Strength")
  if (!all(required_columns %in% colnames(snp2peak_map))) {
    stop(paste("Input data frame must contain the following columns:", paste(required_columns, collapse = ", ")))
  }

  # Ensure weights are numeric
  if (!is.numeric(w1) || !is.numeric(w2)) {
    stop("Both 'w1' and 'w2' must be numeric.")
  }

  # Step 2: Replace missing values
  snp2peak_map <- snp2peak_map %>%
    dplyr::mutate(
      snp_id = ifelse(is.na(snp_id), "no_snp", as.character(snp_id)), # Replace NA in snp_id with 'no_snp'
      Significance = ifelse(is.na(Significance), 0, as.numeric(Significance)), # Replace NA in Significance with 0
      Strength = as.numeric(Strength) # Ensure Strength is numeric
    )

  # Step 3: Calculate weighted importance scores
  snp2peak_map <- snp2peak_map %>%
    dplyr::mutate(
      Importance_weighted = w1 * Strength + w2 * Significance # Formula: Weighted sum of Strength and Significance
      #Importance_weighted = Strength * Significance
    )

  # Step 4: Return the updated data frame
  return(snp2peak_map)
}
